import { Accommodation } from './types';

export const ACCOMMODATIONS: Accommodation[] = [
  {
    id: 'haute-haus',
    name: 'Haute Haus Guest House',
    address: 'Rua Vereador Osni Ortiga, 789, Lagoa da Conceição',
    lat: -27.613124504508107,
    lng: -48.46320450026382,
    distanceToVenue: '0m',
    needsCar: false,
    rating: 9.4,
    ratingLabel: 'Fantástico',
    priceRange: '$$$',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=2070&auto=format&fit=crop',
    bookingUrl: null,
    phone: null,
    amenities: ['Piscina', 'Café da manhã', 'Wi-Fi', 'Estacionamento', 'Pet Friendly'],
    idealFor: 'Noivos / Família VIP',
    vibe: 'Boutique & Sofisticado',
    description: 'O cenário do nosso "sim". Uma propriedade boutique que une o charme de uma casa de campo com a sofisticação de um hotel de design. Situada às margens da Lagoa, oferece a conveniência absoluta para quem deseja estar no centro da ação.',
    cluster: 'venue',
    isVenue: true,
  },
  {
    id: 'jardim-da-lagoa',
    name: 'Pousada Jardim da Lagoa',
    address: 'Rua Vereador Osni Ortiga, 887, Lagoa da Conceição',
    lat: -27.614214646275514,
    lng: -48.46268245809206,
    distanceToVenue: '~150m',
    needsCar: false,
    rating: 8.1,
    ratingLabel: 'Muito Bom',
    priceRange: '$$',
    imageUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=2070&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/hotel/br/eco-hostel-jardim-da-lagoa.pt-br.html',
    phone: null,
    amenities: ['Jardim', 'Bar', 'Acessibilidade', 'Wi-Fi', 'Estacionamento', 'Pet Friendly'],
    idealFor: 'Idosos / Pragmáticos',
    vibe: 'Eco & Conveniência',
    description: 'A Vizinha Prática. Localizada a menos de 200 metros do casamento. Se você quer estacionar o carro na chegada e só usá-lo na hora de ir embora, esta é a sua escolha. Ambiente eco-friendly, acessível e cercado de verde.',
    cluster: 'osni_ortiga',
  },
  {
    id: 'dunas-do-sol',
    name: 'Pousada Dunasol',
    address: 'Rua Vereador Osni Ortiga, 2433, Lagoa da Conceição',
    lat: -27.626798024033413,
    lng: -48.46966434746811,
    distanceToVenue: '~1.6km',
    needsCar: false,
    rating: 8.5,
    ratingLabel: 'Muito Bom',
    priceRange: '$$',
    imageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?q=80&w=2080&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/hotel/br/pousada-dunasol.pt-br.html',
    phone: null,
    amenities: ['Piscina', 'Quadra de Tênis', 'Churrasqueira', 'Recepção 24h', 'Pet Friendly'],
    idealFor: 'Famílias com Crianças',
    vibe: 'Resort & Lazer',
    description: 'Mini-Férias em Família. Com piscina grande, quadra de tênis e muito espaço, é perfeita para famílias com crianças ou grupos de amigos que querem aproveitar o fim de semana como um resort.',
    cluster: 'osni_ortiga',
  },
  {
    id: 'hotel-hola',
    name: 'Hotel Hola',
    address: 'Rua Crisógono Vieira da Cruz, 304, Lagoa da Conceição',
    lat: -27.6029876535716,
    lng: -48.469901088280515,
    distanceToVenue: '~3km',
    needsCar: true,
    rating: 8.1,
    ratingLabel: 'Muito Bom',
    priceRange: '$$',
    imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=2070&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/hotel/br/hola-lagoa.pt-br.html',
    phone: null,
    amenities: ['Piscina', 'Recepção 24h', 'TV LCD', 'À prova de som', 'Estacionamento'],
    idealFor: 'Urbanos / Tradicionais',
    vibe: 'Hotelaria Clássica & Arte',
    description: 'Conforto Urbano. Para quem não abre mão da estrutura de hotel tradicional. Fica no centrinho da Lagoa, perto de farmácias, bancos e supermercados. Ideal para quem quer explorar o agito noturno da região nos dias pré-casamento.',
    cluster: 'centro',
  },
  {
    id: 'quintal-verde',
    name: 'Pousada Quintal Verde',
    address: 'Avenida das Rendeiras, 1046, Lagoa da Conceição',
    lat: -27.608234005060126,
    lng: -48.45369821228753,
    distanceToVenue: '~2.5km',
    needsCar: true,
    rating: 8.0,
    ratingLabel: 'Muito Bom',
    priceRange: '$$',
    imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?q=80&w=2025&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/hotel/br/pousada-quintal-verde.pt-br.html',
    phone: null,
    amenities: ['Café da manhã buffet', 'Wi-Fi', 'Vista Lagoa', 'Pet Friendly'],
    idealFor: 'Turistas "Raiz"',
    vibe: 'Familiar & Pé na Areia',
    description: 'A autêntica experiência da Ilha: acorde de frente para a Lagoa. Localizada na icônica Avenida das Rendeiras, coloca você dentro do cartão postal.',
    cluster: 'rendeiras',
  },
  {
    id: 'casa-da-lagoa',
    name: 'Pousada Casa da Lagoa',
    address: 'Servidão das Palmeiras Nativas, 500, Lagoa da Conceição',
    lat: -27.607547159707273,
    lng: -48.46749880963918,
    distanceToVenue: '~3km',
    needsCar: true,
    rating: 9.6,
    ratingLabel: 'Excepcional',
    priceRange: '$$',
    imageUrl: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?q=80&w=2032&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/hotel/br/pousada-casa-da-lagoa.pt-br.html',
    phone: null,
    amenities: ['Piscina', 'Smart TV', 'Jardim', 'Vista Lagoa', 'Guarda-sóis'],
    idealFor: 'Amantes de Praia',
    vibe: 'Pousada de Veraneio',
    description: 'O ponto de partida ideal para os amantes da praia e das dunas. Situado em uma servidão próxima às Rendeiras, oferece equilíbrio entre agitação e silêncio.',
    cluster: 'rendeiras',
  },
  {
    id: 'lembranca',
    name: 'Pousada Lembrança',
    address: 'Próximo à Avenida das Rendeiras, Lagoa da Conceição',
    lat: -27.609519064289223,
    lng: -48.44738463560329,
    distanceToVenue: '~2.5km',
    needsCar: true,
    rating: 8.0,
    ratingLabel: 'Muito Bom',
    priceRange: '$',
    imageUrl: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?q=80&w=1974&auto=format&fit=crop',
    bookingUrl: null,
    phone: null,
    amenities: ['Cozinha Compartilhada', 'Churrasqueira', 'Varanda', 'Wi-Fi', 'Pet Friendly'],
    idealFor: 'Jovens / Econômicos',
    vibe: 'Simples & Independente',
    description: 'Economia e liberdade: sinta-se em casa com cozinha à disposição. Pequena, intimista e ideal para quem busca economia sem abrir mão da localização.',
    cluster: 'rendeiras',
  },
  {
    id: 'santarina',
    name: 'Pousada Santarina',
    address: 'Servidão da Magia, 75, Canto da Lagoa',
    lat: -27.629779753442758,
    lng: -48.473752117681435,
    distanceToVenue: '~4km',
    needsCar: true,
    rating: 9.8,
    ratingLabel: 'Excepcional',
    priceRange: '$$$',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/hotel/br/pousada-santarina.pt-br.html',
    phone: null,
    amenities: ['Café no Jardim', 'Redários', 'Arquitetura Colonial', 'Multilíngue'],
    idealFor: 'Casais Maduros / Zen',
    vibe: 'Rústico-Chique & Paz',
    description: 'Charme rústico e silêncio absoluto para recarregar as energias. Arquitetura colonial, muita madeira, jardins impecáveis e caminhos de pedra.',
    cluster: 'retiro',
  },
  {
    id: 'essencia-do-sol',
    name: 'Essência do Sol',
    address: 'Servidão Manoel Luiz Duarte, 435, Lagoa da Conceição',
    lat: -27.610515707988622,
    lng: -48.45310920362132,
    distanceToVenue: '~2.5km',
    needsCar: true,
    rating: 9.2,
    ratingLabel: 'Fantástico',
    priceRange: '$$$',
    imageUrl: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?q=80&w=2070&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/hotel/br/essencia-do-sol.pt-br.html',
    phone: null,
    amenities: ['Piscina Aquecida', 'Hidromassagem', 'Suítes Temáticas', 'Fogueira'],
    idealFor: 'Casais Jovens / Românticos',
    vibe: 'Temático & Relaxante',
    description: 'Luxo para casais: piscina aquecida e hidromassagem privativa. Suítes temáticas (Bali, Cairo, Mediterrâneo) para uma experiência única.',
    cluster: 'retiro',
  },
];
